name: Check DNS Servers

on:
  push:
    paths:
      - src/check_dns_servers.py
      - .github/workflows/check_dns_servers.yml
  workflow_dispatch:

jobs:
  check-dns-resolvers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          check-latest: true
          cache: "pip"

      - name: Check Python3 Version
        run: python3 --version

      - name: Install Dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

      - name: Check DNS Servers Availability
        run: python3 ./src/check_dns_servers.py
